#!/bin/bash

config="$XDG_CONFIG_HOME/alacritty/alacritty.yml"

if [[ "$1" != 'dark' && "$1" != 'light' ]]; then
	echo >&2 "Usage: theme (dark|light)"
	exit 1
fi

case "$1" in
	dark)
		sed -i.bak 's/^dark-theme:.*/dark-theme: \&theme/; s/^light-theme:.*/light-theme:/' "$config"
		;;
	light)
		sed -i.bak 's/^light-theme:.*/light-theme: \&theme/; s/^dark-theme:.*/dark-theme:/' "$config"
		;;
esac

xrdb -load -D"$(tr /a-z/ /A-Z/ <<< "$1")" ~/.Xresources

clear
