nmap <buffer> <leader>r <Plug>(go-run)
nmap <buffer> <leader>b <Plug>(go-build)
nmap <buffer> <leader>t <Plug>(go-test)
nmap <buffer> <Leader>i <Plug>(go-implements)
nmap <buffer> <Leader>d <Plug>(go-doc)
