#!/usr/bin/env python

import i3pie
import argparse


def parse_args():
    parser = argparse.ArgumentParser(description="Cycle i3 workspaces")
    parser.add_argument("-dry", action="store_true", help="print next workspace without actually moving")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("-next", action="store_true", help="focus next workspace")
    group.add_argument("-prev", action="store_true", help="focus previous workspace")
    return parser.parse_args()


def is_hidden(w):
    return w.name.startswith("_") or w.name.endswith("_")


def main(i3):

    args = parse_args()
    tree = i3.get_tree()

    numbered = []
    labeled = []

    for w in tree.workspaces():
        if is_hidden(w):
            continue
        elif w.name[0].isdigit():
            numbered.append(w)
        else:
            labeled.append(w)

    # workspace order mimics the same order used in the 
    # i3 polybar module
    by_name = lambda w: w.name
    workspaces = sorted(labeled, key=by_name) + sorted(numbered, key=by_name)
    focused = tree.current_workspace()

    if is_hidden(focused):
        w = workspaces[0] if args.next else workspaces[-1]
    else:
        offset = 1 if args.next else -1
        i = workspaces.index(focused) + offset
        w = workspaces[i % len(workspaces)]

    if args.dry:
        print(w.name)
    else:
        i3.command(f'workspace "{w.name}"')


if __name__ == "__main__":
    with i3pie.Connection() as i3:
        main(i3)
