#!/bin/bash

current_workspace_name() {
	i3-msg -t get_workspaces \
		| jq '.[] | select(.focused==true).name' \
		| cut -d "\"" -f 2
}

main() {

	# add a trailing space if the worksapce name is just a number
	local current
	current=$(current_workspace_name)
	if [[ "${current}" =~ ^[0-9]+$ ]]; then
		current="${current} "
	fi

	local opts name
	name="$(grep -o "^[0-9]\\+" <<< "${current}")"

	if (( reset == 1 )); then
		if [[ -z "${name}" ]]; then
			name="$(i3-new-workspace -dry)"
		fi
	elif (( menu == 1 )); then
		opts="-dmenu -p 'Name' -filter '${current}' -theme 'i3-input'"
		name="$(echo | eval "rofi ${opts}")"
		name="$(sed 's/\(\s\+$\|^\s\+\)//g' <<< "${name}")"
	fi

	if [[ -z "${name}" ]]; then
		exit 1
	fi

	i3-msg -q "rename workspace to \"${name}\"" >/dev/null

}

print_help() {
	echo "Usage: "
	echo "  i3-rename-workspace [-menu|-reset]"
	echo
}

parse_args() {
	while (( $# )); do
		if [[ "$1" == "-reset" ]]; then
			reset=1
		elif [[ "$1" == "-menu" ]]; then
			menu=1
		elif [[ "$1" == "-help" ]]; then
			print_help
			exit 0
		else
			echo "Unknown option: $1" 1>&2
			print_help
			exit 1
		fi
		shift
	done
}

reset=0
menu=0

parse_args "$@"

main
