#!/bin/bash

move=
target=

while (( $# )); do
	if [[ "$1" == "-move" ]]; then
		move="$1"
	elif [[ ! "$1" =~ ^- ]]; then
		target="$1"
	else
		echo "Bad argument: $1" >&2
		exit 1
	fi
	shift
done

session=$(t -d "$target")

if [[ -z "$session" ]]; then
	exit 1
fi

exec i3-focus -c "org.wezfurlong.wezterm" -t "^$session - Tmux$" $move -fallback "wezterm -e t $session"
