#!/bin/bash

SCRIPTPATH="$(realpath -s "$0")"
STATE_FILE="${XDG_RUNTIME_DIR}/borg-backup.state"
ERROR_FILE="${XDG_RUNTIME_DIR}/borg-backup.error"

touch "${STATE_FILE}"
touch "${ERROR_FILE}"

clear_error() {
    truncate -s0 "${ERROR_FILE}"
    print_label
}

print_label() {
    local label=
    if [ -s "${STATE_FILE}" ]; then
		label=" Backup"
	fi
    if [ -s "${ERROR_FILE}" ]; then
		label="%{F#ce7d86} Backup%{F-}"
	fi
    if [ -n "${label}" ]; then
        echo "%{A3:${SCRIPTPATH} -clear:}${label}%{A}"
    else
        echo
    fi
}

main() {
    print_label
    while inotifywait -q -e modify "${STATE_FILE}" "${ERROR_FILE}" >/dev/null; do
        print_label
    done
}

case "$1" in
	"") main ;;
	-clear) clear_error & ;;
	*) exit 1 ;;
esac
