#!/bin/bash


_view_log() {
	urxvt -title "$1 - Journalctl" -e journalctl -e -u "$1"
}


_main() {

	if [[ "$1" == left ]]; then

		if [[ ! -e "$errfile" ]]; then
			exit 1
		fi

		archive="$(cat "$errfile")"
		rm -rf "$errfile"

		if [[ "$archive" =~ ^rsync\.net ]]; then
			_view_log borg-backup-rsync
		elif [[ "$archive" =~ MyPassport ]]; then
			_view_log borg-backup-hdd
		fi

		exit 0

	fi

	if [[ "$1" == right ]]; then

		rm -rf "$errfile"
		exit 0

	fi

}


errfile="/run/borg-backup/error"

_main "$@"
