#!/bin/bash

borgdir="/run/borg-backup"
statedir="$HOME/.run/polybar"
state="$statedir/borg-backup"

mkdir -p "$statedir"
touch "$state"

_notify() {
	notify-send -t 3000 "$@"
}

_notify_err() {
	_notify -u critical "$@"
}

_set_prop() {
	local prop=$1 value=$2
	if grep -q "^$prop=" "$state"; then
		sed -i "s:^$prop=.*:$prop=${value//:/\\:}:" "$state"
	else
		echo "$prop=$value" >> "$state"
	fi
}

_get_prop() {
	local value= prop=$1 default=${2:-0}
	value="$(grep -Po "(?<=^$prop=).*" "$state")"
	echo "${value:-$default}"
}

_polybar_visible() {
	xprop -id $(xdo id -N Polybar) | grep -q "window state: Normal"
}

if [[ -e "$borgdir/error" ]]; then

	if (( "$(_get_prop running)" == 1 )); then
		if ! _polybar_visible; then
			_notify_err "Backup Failed" "$(_get_prop archive '')"
		fi
	fi

	_set_prop running 0

	echo '%{F#ce7d86} Backup%{F-}'

elif [[ -e "$borgdir/running" ]]; then

	archive="$(cat "$borgdir/running")"
	if (( "$(_get_prop running)" == 0 )); then
		_set_prop running 1
		_set_prop archive "$archive"
		if ! _polybar_visible; then
			_notify "Backup Started" "$archive"
		fi
	fi

	echo " Backup"

else

	if (( "$(_get_prop running)" == 1 )); then
		if ! _polybar_visible; then
			_notify "Backup Finished" "$(_get_prop archive '')"
		fi
	fi

	_set_prop running 0

	echo ""

fi
