#!/bin/bash

main() {
	print_label
	while true; do
		if read cmd < "$fifo"; then
			case "$cmd" in
				start) touch "$caffeine" ;;
				stop) rm -f "$caffeine" ;;
				toggle) [[ -f "$caffeine" ]] && rm -f "$caffeine" || touch "$caffeine" ;;
			esac
		fi
		print_label
	done
}

print_label() {
	if [[ -f "$caffeine" ]]; then
		echo "%{A1:coffee &:}%{A}"
	else
		echo
	fi
}

scriptpath="$(realpath -s "$0")"
scriptname="$(basename "$scriptpath")"
caffeine="/run/user/$UID/caffeine"
fifo="/tmp/polybar_caffeine.fifo"

if [[ -p "$fifo" ]]; then
	echo "$scriptname: module already running" >&2
	exit 1
fi

mkfifo "$fifo"
trap "rm '$fifo'" 0
main
