#!/bin/bash

current_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$current_dir" || exit 1
source utils


state_get() {
	utils::state_get "$state" "$@"
}


state_set() {
	utils::state_set "$state" "$@"
}


open_menu() {
	local styles=(default seconds utc)
	local entries="default\\nshow seconds\\nutc time"
	local style="$(state_get style)"
	local choice="$(echo -e "$entries" | i3-tiny-menu -format i -select "$style")"
	if [[ -z "$choice" ]]; then
		return 1
	fi
	state_set style "${styles[$choice]}"
}


main() {
	local style="$(state_get style)"
	case "$style" in
		utc)
			echo "$(date --utc '+%a %d %H:%M') UTC"
			;;
		seconds)
			date '+%a %d %H:%M:%S'
			;;
		*)
			date '+%a %d %H:%M'
			;;
	esac
}


statedir="$HOME/.local/share/polybar"
state="$statedir/datetime"

mkdir -p "$statedir"
touch "$state"

case "$1" in
	-menu)
		open_menu
		;;
	*)
		main "$@"
		;;
esac
