#!/bin/bash

STATE="$HOME/.cache/polybar-datetime.state"
FORMATS=(def sec utc est pst)

CURRENT="$(cat "${STATE}" 2>/dev/null)"
if [ -z "${CURRENT}" ]; then
    CURRENT="${FORMATS[0]}"
fi

print_label() {
    local label
    case "${CURRENT}" in
        def) label=$(date +"%a %d %H:%M") ;;
        sec) label=$(date +"%a %d %H:%M:%S") ;;
        utc) label=$(date -u +"%a %d %H:%M UTC") ;;
        est) label=$(TZ=America/New_York date +"%a %d %H:%M EST") ;;
        pst) label=$(TZ=America/Los_Angeles date +"%a %d %H:%M PST") ;;
        *) label="unknown format" ;;
    esac
    echo "%{A1:kill -USR1 $$:}${label}%{A}"
}

trap 'next_format' USR1
next_format() {
    local len=${#FORMATS[@]}
    for i in "${!FORMATS[@]}"; do
       if [[ "${FORMATS[$i]}" == "${CURRENT}" ]]; then
            CURRENT="${FORMATS[$(((i + 1) % len))]}"
            break
       fi
    done
}

trap 'save_state' 0
save_state() {
    echo -n "${CURRENT}" > "${STATE}"
}

main() {
    while true; do
        print_label
        sleep 1s &
        wait $!
    done
}

main
