#!/bin/bash

if="${1:-eth0}"

state_up() {
	ip addr | grep -q ": $if:.* state UP "
}

ip_addr() {
	ip addr | grep -A3 ": $if:" | grep -Po "(?<=inet )[0-9.]+"
}

draw_block() {
	local addr="$(ip_addr)"
	if [[ -n "$addr" ]]; then
		echo " $addr"
	fi
}

state_up && draw_block
