#!/usr/bin/python -u

import os
import i3ipc
import atexit
import signal
import threading
from pathlib import Path
from threading import Thread


FIFO = Path("/tmp/polybar_i3.fifo")


class Colors:

    dim    = {'fg': '#aaaaaa', 'bg': '#e7e8eb'}
    normal = {'fg': '#52565e', 'bg': '#e7e8eb'}
    active = {'fg': '#52565e', 'bg': '#c2c7ce'}
    urgent = {'fg': '#e7e8eb', 'bg': '#ce7d86'}
    mode   = {'fg': '#e7e8eb', 'bg': '#ce7d86'}


def padded(s):
    return f'  {s}  '


def clickable(s, btn=1, cmd=''):
    cmd = cmd.replace(':', '\:')
    return f'%{{A{btn}:{cmd}:}}{s}%{{A}}'


def colored(s, fg=None, bg=None):
    rv = s
    rv = f'%{{B{bg}}}{rv}%{{B-}}' if bg else rv
    rv = f'%{{F{fg}}}{rv}%{{F-}}' if fg else rv
    return rv


def draw(i3, mode=None, all=False):

    out = ''
    hidden = ''
    mode_ = mode and mode != 'default'

    tree = i3.get_tree()
    active = tree.find_focused().workspace()

    for w in tree.workspaces():
        if not all and w.name.startswith('_') and not w is active:
            hidden += '›'
            continue
        colors = Colors.normal
        if w is active:
            colors = Colors.active
        elif w.urgent:
            colors = Colors.urgent
        block = colored(padded(w.name), **colors)
        if mode_:
            out += block
        else:
            out += clickable(block, cmd=f'i3-msg workspace {w.name}')

    if hidden:
        block = colored(padded(hidden), **Colors.dim)
        out += clickable(block, cmd=f'echo all > {FIFO}')

    if mode_:
        out += colored(padded(mode), **Colors.mode)

    print(out)


def listen_i3(i3):

    def on_workspace(self, e):
        draw(self)

    def on_mode_change(self, e):
        draw(self, mode=e.change)

    i3.on('workspace::focus', on_workspace)
    i3.on('workspace::urgent', on_workspace)
    i3.on('workspace::rename', on_workspace)
    i3.on('window::move', on_workspace)
    i3.on('window::close', on_workspace)
    i3.on('mode', on_mode_change)

    i3.main()


def listen_fifo(i3):
    while True:
        msg = FIFO.read_text().strip()
        if msg == 'all':
            draw(i3, all=True)


def main():

    try:
        os.mkfifo(FIFO)
    except FileExistsError:
        pass

    def cleanup(*args):
        try:
            FIFO.unlink()
        except FileNotFoundError:
            pass

    atexit.register(cleanup)
    signal.signal(signal.SIGINT, cleanup)
    signal.signal(signal.SIGTERM, cleanup)

    i3 = i3ipc.Connection()

    draw(i3)

    Thread(target=listen_i3, args=(i3,), daemon=True).start()
    listen_fifo(i3)


if __name__ == '__main__':
    main()
