#!/bin/bash

SCRIPTPATH="$(realpath -s "$0")"

trap 'clear_all' USR2
clear_all() {
    lib -a -q
    echo
}

trap 'refresh' USR1
refresh() {
    kill ${sleep_pid} 2>/dev/null
}

open_term() {
    kitty --title Lib -e /bin/bash -c "lib -i"
    kill -USR1 $(pgrep -f /polybar/modules/lib)
}

print_count() {
    local label=""
    local count=$(lib -c)
    if (( count > 0 )); then
        label+=" ${count}"
    fi
    lib -l
    local error=$?
    if (( error == 1 )); then
        label="%{F#ce7d86}${label}%{F-}"
    fi
    if (( count > 0 || error == 1 )); then
        echo "%{A3:kill -USR2 $$:}%{A1:${SCRIPTPATH} -view:}${label}%{A}%{A}"
    else
        echo
    fi
}

sleep_pid=
main() {
    while true; do
        print_count
        sleep infinity &
        sleep_pid=$!
        wait $!
    done
}

case "$1" in
	"") main ;;
	-view) open_term & ;;
	*) exit 1 ;;
esac
