#!/bin/bash

stop_recording() {
	if [[ -f "$pidfile" ]]; then
		local file="$(cat "$metafile")"
		kill "$(cat "$pidfile")"
		if [[ -n "$file" ]]; then
			nemo "$file" &
		fi
	fi
}

main() {
	local output="%{A1:$scriptpath stop:} Rec%{A}"
	if [[ -f "$pidfile" ]]; then
		echo "$output"
	fi
	while true; do
		if read -r cmd < "$fifo"; then
			case $cmd in
				start) echo "$output" ;;
				stop) echo ;;
			esac
		fi
	done
}

err() {
	echo "$scriptname: $*" >&2
	exit 1
}

scriptpath="$(realpath -s "$0")"
scriptname="$(basename "$scriptpath")"
fifo="/tmp/polybar_recording.fifo"

pidfile="/run/user/$UID/rec.pid"
metafile="/run/user/$UID/rec.out"

if (( $# == 0 )); then
	if [[ -p "$fifo" ]]; then
		err "module already running"
	fi
	mkfifo "$fifo"
	trap "rm '$fifo'" 0
	main
elif [[ "$1" == 'stop' ]]; then
	if [[ ! -p "$fifo" ]]; then
		err "module not running"
	fi
	stop_recording
fi
