#!/bin/bash


stop_recording() {
	if [[ -f "$pidfile" ]]; then
		local file="$(cat "$metafile")"
		kill "$(cat "$pidfile")"
		echo stop > "$fifo"
	fi
	if [[ -n "$file" ]]; then
		i3-msg "exec --no-startup-id nemo $file"
	fi
}


main() {
	local output=" Recording"
	if [[ -f "$pidfile" ]]; then
		echo "$output"
	fi
	while true; do
		if read -r cmd < "$fifo"; then
			case $cmd in
				start) echo "$output" ;;
				stop) echo ;;
			esac
		fi
	done
}


pidfile="/run/user/$UID/rec.pid"
metafile="/run/user/$UID/rec.out"

fifo="/tmp/polybar_recording.fifo"
if [[ ! -p "$fifo" ]]; then
	mkfifo "$fifo"
fi
trap "rm '$fifo'" 0

case "$1" in
	-stop) stop_recording ;;
	*) main ;;
esac
