#!/bin/bash

format_time() {
	local t=$1
	local d=$(( t / 60 / 60 / 24 ))
	local h=$(( t / 60 / 60 % 24 ))
	local m=$(( t / 60 % 60 ))
	local s=$(( t % 60 ))
	local out="$(printf "%02d" $s)"
	(( m > 0 )) && out="$(printf "%02d" $m):$out"
	(( h > 0 )) && out="$h:$out"
	(( d > 0 )) && out="$d:$out"
	(( m == 0 && h == 0 && d == 0 )) && out="${out}s"
	echo "$out"
}

stopwatch() {
	local elapsed
	local start=$(date +%s)
	while true; do
		elapsed="$(format_time $(( $(date +%s) - start )))"
		echo "%{A1:$scriptpath stop:}%{A3:$scriptpath start:} $elapsed%{A}%{A}"
		sleep 1
	done
}

main() {
	local pid
	while true; do
		if read -r cmd < "$fifo"; then
			case $cmd in
				start)
					if [[ -n "$pid" ]]; then
						kill $pid
					fi
					stopwatch &
					pid=$!
					;;
				stop)
					if [[ -n "$pid" ]]; then
						kill $pid
					fi
					echo
					pid=
					;;
				toggle)
					if [[ -n "$pid" ]]; then
						kill $pid
						echo
						pid=
					else
						stopwatch &
						pid=$!
					fi
					;;
			esac
		fi
	done
}

err() {
	echo "$scriptname: $*" >&2
	exit 1
}

scriptpath="$(realpath -s "$0")"
scriptname="$(basename "$scriptpath")"
fifo="/tmp/polybar_stopwatch.fifo"

if (( $# == 0 )); then
	if [[ -p "$fifo" ]]; then
		err "module already running"
	fi
	mkfifo "$fifo"
	trap "rm '$fifo'" 0
	main
else
	if [[ ! -p "$fifo" ]]; then
		err "module not running"
	fi
	echo "$1" > "$fifo"
fi
