#!/bin/bash

TIMER_START_TIME=0
TIMER_STATE_FILE="$HOME/.cache/polybar-timer.state"
TIMERS=(60 45 30 25 20 15 10 5 4 3 2 1)

CURRENT_TIMER="$(cat "${TIMER_STATE_FILE}" 2>/dev/null)"
if [ -z "${CURRENT_TIMER}" ]; then
    CURRENT_TIMER="30"
fi

format_time() {
    local sign out
    (( $1 >= 0 )) && sign="" || sign="-"
    local t=${1#-}
    local d=$(( t / 60 / 60 / 24 ))
    local h=$(( t / 60 / 60 % 24 ))
    local m=$(( t / 60 % 60 ))
    local s=$(( t % 60 ))
    (( s > 0 || m > 0 )) && out="${s}s"
    (( m > 0 || h > 0 )) && out="${m}m ${out}"
    (( h > 0 || d > 0 )) && out="${h}h ${out}"
    (( d > 0 )) && out="${d}d ${out}"
    (( s == 0 && m == 0 && h == 0 && d == 0 )) && out="0s"
    echo "${sign}${out}"
}

print_label() {
    local label remaining_time formatted_time
    case "${TIMER_START_TIME}" in
        0)
            label=" timer"
            ;;
        *)
            remaining_time=$(( TIMER_START_TIME + CURRENT_TIMER * 60 - $(date +%s) ))
            formatted_time="$(format_time ${remaining_time})"
            if (( remaining_time > 0 )); then
                label=" ${formatted_time}"
            else
                label="%{F#ce7d86} ${formatted_time}%{F-}"
            fi
            ;;
    esac
    echo "%{A1:kill -USR1 $$:}%{A3:kill -USR2 $$:}${label}%{A}%{A}"
}

trap 'toggle_timer' USR1
toggle_timer() {
    case "${TIMER_START_TIME}" in
        0) TIMER_START_TIME=$(date +%s) ;;
        *) TIMER_START_TIME=0 ;;
    esac
}

trap 'choose_timer' USR2
choose_timer() {
    local choice
    choice="$(IFS=$'\n'; echo "${TIMERS[*]}" | mouse-menu -width auto 2>/dev/null)"
    if [[ -n "${choice}" ]]; then
        CURRENT_TIMER="${choice}"
        TIMER_START_TIME=$(date +%s)
        echo -n "${CURRENT_TIMER}" > "${TIMER_STATE_FILE}"
    fi
}

main() {
    while true; do
        print_label
        sleep 1s &
        wait $!
    done
}

main
