#!/bin/bash

SCRIPTPATH="$(realpath -s "$0")"
UPDATES_FILE="$HOME/.local/share/updates-check.state"
touch "${UPDATES_FILE}"

main() {
    display_updates
    while inotifywait -q -e modify "${UPDATES_FILE}" >/dev/null; do
        display_updates
    done
}

display_updates() {
    local count=$(grep -v "^$" "${UPDATES_FILE}" | wc -l)
    if (( count > 0 )); then
        echo "%{A1:$SCRIPTPATH -tmux:}%{A3:$SCRIPTPATH -menu:} ${count}%{A}%{A}"
    else
        echo
    fi
}

open_tmux() {
	local session=updates
	if ! tmux has -t "=${session}" 2>/dev/null; then
		tmux new -ds "${session}"
	fi
	wezterm start --class wez-floating -e t "${session}"
}

updates_menu() {
	local choice="$(sed 's;^\(\S\+\)\s\+\(.*\)$;\1 <span foreground="#999">\2</span>;' < "${UPDATES_FILE}" \
		| mouse-menu -noselected -width auto -markup-rows -maxlines 40)"
	if [[ -n "${choice}" ]]; then
        open_tmux
    fi
}

case "$1" in
	"") main ;;
	-tmux) open_tmux & ;;
	-menu) updates_menu & ;;
	*) exit 1 ;;
esac
