#!/bin/bash

scriptpath="$(realpath -s "$0")"
pidfile="/run/user/$UID/polybar_updates.pid"
updatesfile="/run/user/$UID/polybar_updates.updates"

cleanup() {
	rm "$pidfile" "$updatesfile"
}

main() {
	trap "cleanup" 0
	local n
	while true; do
		n="$(checkupdates | tee "$updatesfile" | wc -l)"
		if (( n > 0 )); then
			echo "%{A1:$scriptpath view:}%{A3:$scriptpath quickview:} $n%{A}%{A}"
		else
			echo ""
		fi
		sleep 1h &
		echo $! > "$pidfile"
		wait
	done
}

view() {
	local session=updates
	if ! tmux has -t "=$session" 2>/dev/null; then
		tmux new -ds "$session"
	fi
	urxvt -name floating -e t "$session"
}

quickview() {
	local choice="$(sed 's;^\(\S\+\)\s\+\(.*\)$;\1 <span foreground="#999">\2</span>;' < "$updatesfile" \
		| mouse-menu -noselected -width auto -markup-rows -maxlines 40)"
	[[ "$choice" ]] && view
}

case "$1" in
	"") main ;;
	view) view & ;;
	quickview) quickview & ;;
	*) exit 1 ;;
esac
