#!/bin/bash

print_label() {
	local label
	local volume="$(amixer -D pulse sget Master | grep -Pom1 '[0-9]+(?=%)')"
	if amixer -D pulse sget Master | grep -q '\[off\]'; then
		label=" Mute"
	elif (( volume < 25 )); then
		label=" $volume%"
	elif (( volume < 50 )); then
		label=" $volume%"
	else
		label=" $volume%"
	fi
	echo "%{A4:volume up:}%{A5:volume down:}%{A1:volume toggle:}$label%{A}%{A}%{A}"
}

print_label
pactl subscribe | while read -r _ event _ type _; do
	if [[ "$event" == "'change'" && "$type" == 'sink' ]]; then
		print_label
	fi
done
