#!/bin/bash

markers="$(IFS=$'\n'; echo "$*")"

find_root() {
	if [[ "$1" == '/' || -z "$1" ]]; then
		return 1
	fi
	cd "$1" || return 1
	if ls -Ap | grep -Fxq -f <(echo "$markers"); then
		vifm --server-name "$VIFM_SERVER" --remote +"cd \"$1\""
		return $?
	fi
	find_root "$(dirname "$1")"
}

find_root "$PWD"
exit $?
