#!/bin/bash

cwd="${PWD/#$HOME/\~}"
header="$(tput bold)$(tput setaf 5)${cwd}$(tput sgr0)"
FZF_DEFAULT_OPTS+=" --header='${header}'"

FZF_DEFAULT_OPTS+=" --color prompt:19,info:19,pointer:24"
FZF_DEFAULT_OPTS+=" --ansi --inline-info --no-bold --bind 'tab:down,shift-tab:up'"
FZF_DEFAULT_OPTS+=" --preview '[ -d {} ] && tree {} -L 1 || head -100 {}'"

d=
if (( $# > 0 )); then
	d="--directory"
fi

target="$(LC_COLLATE=C ls -A1p $d --color=always --group-directories-first "$@" | fzf 2>/dev/tty)"
if [[ -n "${target}" ]]; then
	vifm --server-name "$VIFM_SERVER_NAME" --remote +"goto \"${target}\""  +"norm! l"
fi
