#!/bin/bash

clear

FZF_DEFAULT_OPTS+=" --color prompt:19,info:19,pointer:24,info:22"
FZF_DEFAULT_OPTS+=" --bind 'tab:down,shift-tab:up'"

if [[ "$1" == '-cd' ]]; then
	shift
	target="$(fd -td --hidden -E .git -E __pycache__ "$@" | fzf 2>/dev/tty)"
	cmd='goto'
else
	target="$(rg --files --hidden -g "!.git/" -g "!*.pyc" "$@" | fzf 2>/dev/tty)"
	cmd='edit'
fi

if [[ -n "${target}" ]]; then
	vifm --server-name "$VIFM_SERVER_NAME" --remote +"${cmd} \"${target}\""
fi
