#!/bin/bash

markers=("$@")

find_root() {
	if [[ "$1" == '/' || -z "$1" ]]; then
		return 1
	fi
	cd "$1" || exit 1
	for marker in "${markers[@]}"; do
		if ls -Ap | grep -Fxq -- "$marker"; then
			vifm --server-name "$VIFM_SERVER_NAME" --remote +"cd \"$1\""
			return $?
		fi
	done
	find_root "$(dirname "$1")"
}

find_root "$PWD"
exit $?
