#!/bin/bash

clear

cwd="${PWD/#$HOME/\~}"
header="$(tput bold)$(tput setaf 5)${cwd}$(tput sgr0)"
FZF_DEFAULT_OPTS+=" --header='${header}'"

FZF_DEFAULT_OPTS+=" --color prompt:19,info:19,pointer:24"
FZF_DEFAULT_OPTS+=" --ansi --inline-info --no-bold --bind 'tab:down,shift-tab:up'"

target="$(LC_COLLATE=C ls -A1p --color=always --group-directories-first "$@" | fzf 2>/dev/tty)"
if [[ -n "${target}" ]]; then
	after=
	if [[ -d "${target}" ]]; then
        # after=fzfilter
        after=
	fi
	vifm --server-name "$VIFM_SERVER" --remote +"goto \"${target}\""  +"norm! l" +"${after}"
fi
