
export QT_QPA_PLATFORMTHEME=qt5ct

xrdb -load ~/.Xresources

setxkbmap -layout it

xmodmap ~/.Xmodmap

xset s off dpms 0 0 0

xset r rate 175 25

xautolock &

sh ~/.config/dunst/start.sh &

compton -b

nitrogen --restore &

mpd

tmux new -ds scratch 2>/dev/null

exec i3
